### ISSUE TITLE
Cannot Update OAK via wifi or direct

### ISSUE THREAD

**Issue by Manxtu** [digistump/OakUpdateTool#1]
C:\oak>oakupsrv
This version of C:\oak\oakupsrv.exe is not compatible with the version of Windows you're running. Check your compu
 whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

Running Win7 on a 32 bit machine - can you help

Mike

**Comment by digistump** [comment]
Please try this version which should work on 32 and 64 bit: https://github.com/digistump/OakUpdateTool/releases/download/1.0.0/oakupsrv-win32-r2.zip

**Comment by Manxtu** [comment]
Followed instructions to the tee and now no wifi from device and triple flashes 

Wonder where to go now - I have 3 devices ready to flash but wary Im going to brick the opther two!

Mike
